"""add_role_to_users

Revision ID: 061562313a13
Revises: 8bb83c9cefe9
Create Date: 2026-04-21 11:31:24.297767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '061562313a13'
down_revision: Union[str, Sequence[str], None] = '8bb83c9cefe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_expanded_view')
    op.drop_table('readings_expanded_view')
    op.add_column('users', sa.Column('role', sa.String(length=10), nullable=True))
    op.execute("""
        UPDATE users
        SET role = 'user'
        WHERE role IS NULL
    """)
    op.alter_column('users', 'role', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_table('readings_expanded_view',
    sa.Column('reading_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pages_read', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personal_goal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('club_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_publication_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publisher_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('format_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reading_tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reading_shelves', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('reading_id', name=op.f('readings_expanded_view_pkey'))
    )
    op.create_table('books_expanded_view',
    sa.Column('book_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_publication_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publisher_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('collection_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('format_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('format_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reading_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pages_read', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('personal_goal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('club_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('club_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reading_status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reading_status_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reading_tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reading_shelves', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id', name=op.f('books_expanded_view_pkey'))
    )
    # ### end Alembic commands ###
