"""add rating to readings

Revision ID: 79abea4b25b0
Revises: abc40134d384
Create Date: 2026-08-16 13:11:33.565088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79abea4b25b0'
down_revision: Union[str, Sequence[str], None] = 'abc40134d384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readings', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'rating')
    # ### end Alembic commands ###
