"""Add synopsis and review

Revision ID: abc40134d384
Revises: 061562313a13
Create Date: 2026-08-12 16:44:00.321073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc40134d384'
down_revision: Union[str, Sequence[str], None] = '061562313a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('synopsis', sa.Text(), nullable=True))
    op.add_column('readings', sa.Column('review', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('readings', 'review')
    op.drop_column('books', 'synopsis')
    # ### end Alembic commands ###
